apiVersion: v1

kind: Pod

metadata:
       labels:
            podname: secondpod 
       name: pod2

spec:
    containers:
            - name: secondpod
              image: coolgourav147/nginx-custom
              env:
               - name: variablefromcm
                 valueFrom:
                   configMapKeyRef:
                           key: variable2
                           name: envcm
    tolerations:
             - effect: "NoSchedule"
               key: "mysize"
               operator: "Equal"
               value: "large"            
