apiVersion: v1

kind: Pod

metadata:
       labels:
            podname: secondpodlbl 
       name: pod

spec:
    containers:
            - name: secondpod
              image: coolgourav147/nginx-custom   
