apiVersion: apps/v1

kind: Deployment

metadata:
        name: mydeploy
        labels:
             name: mydeploy   

spec:
    replicas: 3
    selector:
            matchLabels: 
               app: myapp1
    template:
        metadata: 
             name: secondpod
             labels: 
                 app: myapp1

        spec:
          containers:
                - name: firstcontainer
                  image: coolgourav147/nginx-custom:v2
                      


