apiVersion: v1

kind: Service

metadata:
        name: service
        labels:
                servicelbl: labelname 

spec:
   type: NodePort
   ports:
     - nodePort: 32000
       port: 9000
       targetPort: 80
   selector:
           type: myapp1   

