apiVersion: v1
kind: Pod
metadata:
    name: my-app

spec:
        containers:
                - name: first
                  image: nginx
                  env:
                          - name: myname
                            value: Aman
                          - name: city
                            value: daund  
           #      resources:     
                  #  limits:
               #        memory: "200Mi"     
                            
         
