apiVersion: v1

kind: ReplicationController

metadata:
        name: secondrc
        labels:
             appname: votingapp   

spec:
    replicas: 3 
    template:
        metadata: 
             name: secondpod
             labels: 
                 type: app

        spec:
          containers:
                - name: firstcontainer
                  image: coolgourav147/nginx-custom
                      


