apiVersion: apps/v1

kind: ReplicaSet

metadata:
        name: firstrs
        labels:
             name: firstrs   

spec:
    replicas: 2
    selector:
            matchLabels: 
               app: myapp1
    template:
        metadata: 
             name: secondpod
             labels: 
                 app: myapp1

        spec:
          containers:
                - name: firstcontainer
                  image: coolgourav147/nginx-custom
                      


