apiVersion: v1
kind: Pod
metadata:
    name: firstsecretpod
spec:
  containers:
          - name: newcontainer
            image: coolgourav147/nginx-custom
  #          env:
       #      - name: myvariable
     #          valueFrom:
        #           secretKeyRef:
        #             key: variable1
        #             name: envsecret
            envFrom:      
               - secretRef:  
                  name: envsecret
